#!/bin/bash

FILE_NAME="$1"

if [ -z "$FILE_NAME" ]; then
    echo "File name missing!"
    exit 1
fi

docker run --rm -v "$(dirname "$(readlink -f "$FILE_NAME")")":/source:ro capstone /source/"$(basename "$FILE_NAME")"
